; PlatformIO Project Configuration File

[env:esp32dev]

platform = espressif32

board = esp32dev

framework = arduino


; Serial Monitor

monitor_speed = 115200


; Upload Speed

upload_speed = 115200


; Include Folder

build_flags =
    -I include



; Libraries

lib_deps =
    adafruit/Adafruit Unified Sensor
    adafruit/DHT sensor library@^1.4.7
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^7.0.4
    mobizt/Firebase ESP32 Client@^4.4.14